# Basic
title: Furson 
subtitle: 技术、游戏、生活
welcome_message: <a href="https://github.com/furson" target="_blank">还在填充的某G平台</a>
description: 希望这回能多写几篇2333

# Theme creator
creator: <a href="http://onev.cat">@onevcat</a>
url: "http://furson.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://github.com/furson'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: furson
    github: furson 
    twitter: fursonfu
    mail: fursonfu@gmail.com

# Google Analytics
# ga:
    # id: your_ga_id
    # host: your_host
